twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      navigation:
        topic: cmd_vel_safe
        timeout: 0.2
        priority: 10
      teleop:
        topic: cmd_vel_teleop
        timeout: 0.5
        priority: 100